functionsDirectory = "C:\\Users\\Rom\\Documents\\GitHub\\websocket\\client\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Rom\\Documents\\GitHub\\websocket\\client\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\Rom\\Documents\\GitHub\\websocket\\client"
command = "npm run build"
functions = "C:\\Users\\Rom\\Documents\\GitHub\\websocket\\client\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]